// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"
	"database/sql"
)

const deleteDocumentTags = `-- name: DeleteDocumentTags :exec
DELETE FROM document_tags WHERE document_id = ?
`

func (q *Queries) DeleteDocumentTags(ctx context.Context, documentID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentTags, documentID)
	return err
}

const getDocumentCount = `-- name: GetDocumentCount :one
SELECT COUNT(*) FROM documents
`

func (q *Queries) GetDocumentCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDocumentCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertDocumentTag = `-- name: InsertDocumentTag :exec
INSERT OR IGNORE INTO document_tags (document_id, tag_id) VALUES (?, ?)
`

type InsertDocumentTagParams struct {
	DocumentID sql.NullInt64 `json:"document_id"`
	TagID      sql.NullInt64 `json:"tag_id"`
}

func (q *Queries) InsertDocumentTag(ctx context.Context, arg InsertDocumentTagParams) error {
	_, err := q.db.ExecContext(ctx, insertDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const listRecentDocuments = `-- name: ListRecentDocuments :many
SELECT d.id, d.title, d.correspondent_id, d.document_type_id, d.created, d.added, d.modified, d.archive_serial_number, d.original_file_name, d.page_count
FROM documents d
ORDER BY d.added DESC
LIMIT ?
`

func (q *Queries) ListRecentDocuments(ctx context.Context, limit int64) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CorrespondentID,
			&i.DocumentTypeID,
			&i.Created,
			&i.Added,
			&i.Modified,
			&i.ArchiveSerialNumber,
			&i.OriginalFileName,
			&i.PageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (id, title, correspondent_id, document_type_id, created, added, modified, archive_serial_number, original_file_name, page_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    title = excluded.title,
    correspondent_id = excluded.correspondent_id,
    document_type_id = excluded.document_type_id,
    created = excluded.created,
    added = excluded.added,
    modified = excluded.modified,
    archive_serial_number = excluded.archive_serial_number,
    original_file_name = excluded.original_file_name,
    page_count = excluded.page_count
`

type UpsertDocumentParams struct {
	ID                  int64          `json:"id"`
	Title               string         `json:"title"`
	CorrespondentID     sql.NullInt64  `json:"correspondent_id"`
	DocumentTypeID      sql.NullInt64  `json:"document_type_id"`
	Created             sql.NullString `json:"created"`
	Added               sql.NullString `json:"added"`
	Modified            sql.NullString `json:"modified"`
	ArchiveSerialNumber sql.NullInt64  `json:"archive_serial_number"`
	OriginalFileName    sql.NullString `json:"original_file_name"`
	PageCount           sql.NullInt64  `json:"page_count"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertDocument,
		arg.ID,
		arg.Title,
		arg.CorrespondentID,
		arg.DocumentTypeID,
		arg.Created,
		arg.Added,
		arg.Modified,
		arg.ArchiveSerialNumber,
		arg.OriginalFileName,
		arg.PageCount,
	)
	return err
}
