// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Correspondent struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          sql.NullString `json:"slug"`
	DocumentCount sql.NullInt64  `json:"document_count"`
}

type Document struct {
	ID                  int64          `json:"id"`
	Title               string         `json:"title"`
	CorrespondentID     sql.NullInt64  `json:"correspondent_id"`
	DocumentTypeID      sql.NullInt64  `json:"document_type_id"`
	Created             sql.NullString `json:"created"`
	Added               sql.NullString `json:"added"`
	Modified            sql.NullString `json:"modified"`
	ArchiveSerialNumber sql.NullInt64  `json:"archive_serial_number"`
	OriginalFileName    sql.NullString `json:"original_file_name"`
	PageCount           sql.NullInt64  `json:"page_count"`
}

type DocumentTag struct {
	DocumentID sql.NullInt64 `json:"document_id"`
	TagID      sql.NullInt64 `json:"tag_id"`
}

type DocumentType struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          sql.NullString `json:"slug"`
	DocumentCount sql.NullInt64  `json:"document_count"`
}

type SyncState struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type Tag struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          sql.NullString `json:"slug"`
	Color         sql.NullString `json:"color"`
	DocumentCount sql.NullInt64  `json:"document_count"`
}
