// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteDocumentTags(ctx context.Context, documentID sql.NullInt64) error
	GetCorrespondentCount(ctx context.Context) (int64, error)
	GetDocumentCount(ctx context.Context) (int64, error)
	GetDocumentTypeCount(ctx context.Context) (int64, error)
	GetSyncState(ctx context.Context, key string) (sql.NullString, error)
	GetTagCount(ctx context.Context) (int64, error)
	InsertDocumentTag(ctx context.Context, arg InsertDocumentTagParams) error
	ListCorrespondents(ctx context.Context) ([]Correspondent, error)
	ListDocumentTypes(ctx context.Context) ([]DocumentType, error)
	ListRecentDocuments(ctx context.Context, limit int64) ([]Document, error)
	ListTags(ctx context.Context) ([]Tag, error)
	SetSyncState(ctx context.Context, arg SetSyncStateParams) error
	UpsertCorrespondent(ctx context.Context, arg UpsertCorrespondentParams) error
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error
	UpsertDocumentType(ctx context.Context, arg UpsertDocumentTypeParams) error
	UpsertTag(ctx context.Context, arg UpsertTagParams) error
}

var _ Querier = (*Queries)(nil)
