// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package db

import (
	"context"
	"database/sql"
)

const getSyncState = `-- name: GetSyncState :one
SELECT value FROM sync_state WHERE key = ?
`

func (q *Queries) GetSyncState(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const setSyncState = `-- name: SetSyncState :exec
INSERT INTO sync_state (key, value)
VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetSyncStateParams struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) SetSyncState(ctx context.Context, arg SetSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, setSyncState, arg.Key, arg.Value)
	return err
}
