// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taxonomy.sql

package db

import (
	"context"
	"database/sql"
)

const getCorrespondentCount = `-- name: GetCorrespondentCount :one
SELECT COUNT(*) FROM correspondents
`

func (q *Queries) GetCorrespondentCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCorrespondentCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDocumentTypeCount = `-- name: GetDocumentTypeCount :one
SELECT COUNT(*) FROM document_types
`

func (q *Queries) GetDocumentTypeCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDocumentTypeCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTagCount = `-- name: GetTagCount :one
SELECT COUNT(*) FROM tags
`

func (q *Queries) GetTagCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTagCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCorrespondents = `-- name: ListCorrespondents :many
SELECT id, name, slug, document_count
FROM correspondents
ORDER BY document_count DESC
`

func (q *Queries) ListCorrespondents(ctx context.Context) ([]Correspondent, error) {
	rows, err := q.db.QueryContext(ctx, listCorrespondents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Correspondent
	for rows.Next() {
		var i Correspondent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTypes = `-- name: ListDocumentTypes :many
SELECT id, name, slug, document_count
FROM document_types
ORDER BY document_count DESC
`

func (q *Queries) ListDocumentTypes(ctx context.Context) ([]DocumentType, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentType
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, color, document_count
FROM tags
ORDER BY document_count DESC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCorrespondent = `-- name: UpsertCorrespondent :exec
INSERT INTO correspondents (id, name, slug, document_count)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    slug = excluded.slug,
    document_count = excluded.document_count
`

type UpsertCorrespondentParams struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          sql.NullString `json:"slug"`
	DocumentCount sql.NullInt64  `json:"document_count"`
}

func (q *Queries) UpsertCorrespondent(ctx context.Context, arg UpsertCorrespondentParams) error {
	_, err := q.db.ExecContext(ctx, upsertCorrespondent,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.DocumentCount,
	)
	return err
}

const upsertDocumentType = `-- name: UpsertDocumentType :exec
INSERT INTO document_types (id, name, slug, document_count)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    slug = excluded.slug,
    document_count = excluded.document_count
`

type UpsertDocumentTypeParams struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          sql.NullString `json:"slug"`
	DocumentCount sql.NullInt64  `json:"document_count"`
}

func (q *Queries) UpsertDocumentType(ctx context.Context, arg UpsertDocumentTypeParams) error {
	_, err := q.db.ExecContext(ctx, upsertDocumentType,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.DocumentCount,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO tags (id, name, slug, color, document_count)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    slug = excluded.slug,
    color = excluded.color,
    document_count = excluded.document_count
`

type UpsertTagParams struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          sql.NullString `json:"slug"`
	Color         sql.NullString `json:"color"`
	DocumentCount sql.NullInt64  `json:"document_count"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertTag,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.DocumentCount,
	)
	return err
}
